# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 03:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notifications.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('explore', '\u53d1\u73b0'), ('disney', '\u8fea\u58eb\u5c3c'), ('moments', '\u5708\u5b50'), ('concert', '\u6f14\u5531\u4f1a'), ('aerospace', '\u5b87\u822a\u5957\u9910')], default='', max_length=10)),
                ('content_id', models.IntegerField(blank=True, default=0, verbose_name='\u63a8\u9001\u5185\u5bb9\u5bf9\u5e94id')),
                ('action', models.CharField(choices=[('Comment', '\u8bc4\u8bba\u4e86'), ('Share', '\u5206\u4eab\u4e86'), ('Register', '\u6ce8\u518c\u6210\u529f'), ('Like', '\u6536\u85cf\u4e86'), ('Dislike', '\u53d6\u6d88\u6536\u85cf\u4e86')], default='', max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='\u901a\u77e5\u65f6\u95f4')),
                ('content', models.CharField(blank=True, max_length=200, verbose_name='\u5185\u5bb9')),
                ('banner', models.ImageField(upload_to=notifications.models.post_banner_upload_path, verbose_name='\u6d88\u606f\u5c01\u9762\u7f29\u7565\u56fe')),
                ('is_read', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8bfb')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL, verbose_name='\u63a5\u6536\u8005')),
                ('triggering_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggering_user', to=settings.AUTH_USER_MODEL, verbose_name='\u89e6\u53d1\u4eba')),
            ],
            options={
                'verbose_name': '\u6d88\u606f\u901a\u77e5',
                'verbose_name_plural': '\u6d88\u606f\u901a\u77e5',
            },
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('3', 'Android'), ('4', 'iOS')], default='', max_length=25)),
                ('user_id_baidu', models.CharField(blank=True, default='', max_length=25)),
                ('channel_id', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6d88\u606f',
                'verbose_name_plural': '\u7528\u6237\u6d88\u606f',
            },
        ),
    ]
