# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='device_type',
            field=models.CharField(choices=[('3', 'Android'), ('4', 'iOS')], default='', max_length=1),
        ),
    ]
