# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20160714_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('Comment', '\u8bc4\u8bba\u4e86'), ('Share', '\u5206\u4eab\u4e86'), ('Register', '\u6ce8\u518c\u6210\u529f'), ('Like', '\u6536\u85cf\u4e86'), ('Dislike', '\u53d6\u6d88\u6536\u85cf\u4e86'), ('Approved', '\u901a\u8fc7\u5ba1\u6838'), ('Disapproved', '\u672a\u901a\u8fc7\u5ba1\u6838')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.CharField(choices=[('explore', '\u53d1\u73b0'), ('disney', '\u8fea\u58eb\u5c3c'), ('moments', '\u5708\u5b50'), ('concert', '\u6f14\u5531\u4f1a'), ('aerospace', '\u5b87\u822a\u5957\u9910'), ('agent', '\u4ee3\u7406')], default='', max_length=10),
        ),
    ]
