# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', max_length=140)),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('solved_time', models.DateTimeField(verbose_name='\u89e3\u51b3\u65f6\u95f4')),
                ('is_solved', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u5904\u7406')),
            ],
            options={
                'verbose_name': '\u610f\u89c1\u53cd\u9988',
                'verbose_name_plural': '\u610f\u89c1\u53cd\u9988',
            },
        ),
    ]
