# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='solved_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u89e3\u51b3\u65f6\u95f4'),
        ),
    ]
