# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 10:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import moments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentsComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=140, verbose_name='\u8bc4\u8bba')),
                ('corresponding_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moments_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u5708\u5b50\u8bc4\u8bba',
                'verbose_name_plural': '\u5708\u5b50\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140, verbose_name='\u6b63\u6587')),
                ('banner', models.ImageField(blank=True, upload_to=moments.models.post_image_upload_path, verbose_name='\u5708\u5b50\u5c01\u9762\u56fe')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('corresponding_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_moments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u5708\u5b50',
                'verbose_name_plural': '\u5708\u5b50',
            },
        ),
        migrations.CreateModel(
            name='UserMoments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moments_likes', models.ManyToManyField(blank=True, to='moments.Post', verbose_name='\u5df2\u70b9\u8d5e\u5708\u5b50')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5708\u5b50',
                'verbose_name_plural': '\u7528\u6237\u5708\u5b50',
            },
        ),
    ]
