# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_auto_20160622_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_count',
        ),
    ]
