# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import moments.models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0003_remove_post_liked_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=moments.models.post_image_upload_path, verbose_name='\u5708\u5b50\u5c01\u9762\u56fe'),
        ),
    ]
