# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0004_auto_20160622_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u663e\u793a'),
        ),
    ]
