# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 05:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moments', '0005_post_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='corresponding_user',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='composed_moments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='forward_notes',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='\u8f6c\u53d1\u6587\u5b57'),
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='published_moments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
