# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 03:50
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import explore.models
import vip.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=140, verbose_name='\u8bc4\u8bba')),
            ],
            options={
                'verbose_name': '\u53d1\u73b0\u8bc4\u8bba',
                'verbose_name_plural': '\u53d1\u73b0\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to=vip.utils.get_explore_highlight_upload_path, verbose_name='\u5c01\u9762\u56fe')),
                ('display', models.BooleanField(default=False, verbose_name='\u662f\u5426\u663e\u793a')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('banner', models.ImageField(blank=True, upload_to=explore.models.post_banner_upload_path, verbose_name='\u9876\u90e8\u5c01\u9762\u56fe')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u6b63\u6587')),
            ],
            options={
                'verbose_name': '\u53d1\u73b0',
                'verbose_name_plural': '\u53d1\u73b0',
            },
        ),
        migrations.CreateModel(
            name='UserExplore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explore_likes', models.ManyToManyField(blank=True, to='explore.Post', verbose_name='\u5df2\u6536\u85cf\u53d1\u73b0')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u53d1\u73b0',
                'verbose_name_plural': '\u7528\u6237\u53d1\u73b0',
            },
        ),
        migrations.AddField(
            model_name='highlight',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.Post'),
        ),
        migrations.AddField(
            model_name='explorecomments',
            name='corresponding_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explore_comments', to='explore.Post'),
        ),
        migrations.AddField(
            model_name='explorecomments',
            name='corresponding_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
