# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import vip.utils


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=vip.utils.get_explore_highlight_upload_path, verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
