# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import explore.models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_auto_20160621_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(upload_to=explore.models.post_banner_upload_path, verbose_name='\u9876\u90e8\u5c01\u9762\u56fe'),
        ),
    ]
