# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_auto_20160621_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption_description',
            field=models.CharField(default='默认描述.', max_length=30, verbose_name='\u63a8\u8350\u5185\u5bb9\u63cf\u8ff0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='caption_title',
            field=models.CharField(default='默认标题', max_length=10, verbose_name='\u63a8\u8350\u6807\u9898\u63cf\u8ff0'),
            preserve_default=False,
        ),
    ]
