# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import explore.models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_auto_20160629_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=explore.models.post_video_upload_path, verbose_name='\u5c0f\u89c6\u9891'),
        ),
    ]
