# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_auto_20160729_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.TextField(blank=True, null=True, verbose_name='\u89c6\u9891\u94fe\u63a5'),
        ),
    ]
