# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0008_auto_20160729_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.TextField(blank=True, default='', verbose_name='\u89c6\u9891\u94fe\u63a5'),
        ),
    ]
