# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLabelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('short', models.CharField(max_length=20)),
            ],
        ),
    ]
