# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0005_auto_20160504_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipuser',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='\u6635\u79f0'),
        ),
    ]
