# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0006_vipuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipuser',
            name='pin',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
