# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0008_auto_20160505_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vipuser',
            old_name='pin_update_on',
            new_name='pin_updated_on',
        ),
    ]
