# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0009_auto_20160505_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='\u9a8c\u8bc1\u624b\u673a\u53f7')),
                ('pin', models.CharField(max_length=6, verbose_name='\u9a8c\u8bc1\u7801')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
        migrations.RemoveField(
            model_name='vipuser',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='vipuser',
            name='pin_updated_on',
        ),
    ]
