# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 08:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0011_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': '\u9080\u8bf7\u7801', 'verbose_name_plural': '\u9080\u8bf7\u7801'},
        ),
        migrations.AlterField(
            model_name='promotion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vipuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '\u7537'), ('F', '\u5973')], max_length=1, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='vipuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6635\u79f0'),
        ),
    ]
