# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0012_auto_20160506_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.VIPUser'),
        ),
    ]
