# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0013_auto_20160506_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'verbose_name': '\u624b\u673a\u9a8c\u8bc1\u7801', 'verbose_name_plural': '\u624b\u673a\u9a8c\u8bc1\u7801'},
        ),
        migrations.AlterModelOptions(
            name='vipuser',
            options={'verbose_name': 'VIP\u7528\u6237', 'verbose_name_plural': 'VIP\u7528\u6237'},
        ),
        migrations.AddField(
            model_name='vipuser',
            name='labels',
            field=models.ManyToManyField(to='registrar.UserLabel'),
        ),
    ]
