# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0014_auto_20160506_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipuser',
            name='promoter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrar.VIPUser', verbose_name='\u63a8\u8350\u4eba'),
        ),
        migrations.AlterField(
            model_name='vipuser',
            name='labels',
            field=models.ManyToManyField(blank=True, to='registrar.UserLabel', verbose_name='\u7528\u6237\u6807\u7b7e'),
        ),
    ]
