# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0016_auto_20160506_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VIPUser',
            new_name='Profile',
        ),
    ]
