# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0017_auto_20160507_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u5934\u50cf'),
        ),
        migrations.AddField(
            model_name='userlabelcategory',
            name='allow_multiple',
            field=models.BooleanField(default=False, verbose_name='\u5141\u8bb8\u591a\u9009'),
        ),
    ]
