# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0018_auto_20160513_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='avatar',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='registrar.Profile'),
        ),
        migrations.AlterField(
            model_name='userlabel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='registrar.UserLabelCategory'),
        ),
    ]
