# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0020_auto_20160516_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='\u6635\u79f0'),
        ),
    ]
