# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0021_auto_20160527_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u5168\u79f0')),
                ('code', models.CharField(max_length=20, verbose_name='\u82f1\u6587\u540d\u79f0')),
                ('country', models.CharField(choices=[('CN', '\u4e2d\u56fd'), ('US', '\u7f8e\u56fd'), ('CA', '\u52a0\u62ff\u5927'), ('JP', '\u65e5\u672c'), ('KR', '\u97e9\u56fd')], default='CN', max_length=3, verbose_name='\u56fd\u5bb6')),
            ],
            options={
                'verbose_name': '\u57ce\u5e02',
                'verbose_name_plural': '\u57ce\u5e02',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '\u7528\u6237\u4fe1\u606f', 'verbose_name_plural': '\u7528\u6237\u4fe1\u606f'},
        ),
    ]
