# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0022_auto_20160530_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
