# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0024_auto_20160701_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apply_for_agent',
            field=models.BooleanField(default=False),
        ),
    ]
