# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0026_auto_20160707_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentapplication',
            name='verified',
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='status',
            field=models.IntegerField(choices=[(-1, '\u7533\u8bf7\u62d2\u7edd'), (0, '\u7b49\u5f85\u5ba1\u6838'), (1, '\u7533\u8bf7\u6210\u529f')], default=0, verbose_name='\u7533\u8bf7\u72b6\u6001'),
        ),
    ]
