# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0028_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emchatpd',
            field=models.CharField(blank=True, max_length=8, verbose_name='\u73af\u4fe1\u5bc6\u7801'),
        ),
        migrations.AddField(
            model_name='profile',
            name='emchatuser',
            field=models.CharField(blank=True, max_length=16, verbose_name='\u73af\u4fe1\u8d26\u53f7'),
        ),
    ]
