# order expire minutes
expire_minutes: 600

# ============== TEST ==============
# test env merchant id
merchant_id: '777290058132172'
# test env cfca file path
pfx_filepath: unionpay/pem/acp01.pfx
# test env cfca PEM password
password: '000000'
# test env x509 cert path
x509_filepath: unionpay/pem/acp_test_verify_sign_new.cer
# ==================================

# ============= PRODUCTION ==================
## cayman prod env merchant id
#merchant_id: '898310154110588'
## cayman prod env cfca file path
#pfx_filepath: unionpay/pem/vip_unionpay_160620.pfx
## cayman prod env cfca PEM password
#password: '160620'
## caymen prod env x509 cert path
#x509_filepath: unionpay/pem/acp_prod_verify_sign.cer
# ===========================================


# digest method
digest_method: sha1
# notify url for back notify from unionpay
backend_url: http://120.76.126.214:8000/unionpay_callback
#backend_url: http://171.221.244.120:8000/unionpay_callback


# unionpay trade address
# ============================== TEST ==============================
app_trans_url: https://101.231.204.80:5000/gateway/api/appTransReq.do
front_trans_url: https://101.231.204.80:5000/gateway/api/frontTransReq.do
back_trans_url: https://101.231.204.80:5000/gateway/api/backTransReq.do
card_back_trade: https://101.231.204.80:5000/gateway/api/cardTransReq.do
single_query_url: https://101.231.204.80:5000/gateway/api/queryTrans.do
batch_trans_url: https://101.231.204.80:5000/gateway/api/batchTrans.do
file_trans_url: https://101.231.204.80:9080/
# ==================================================================

# ============================== PRODUCTION ==============================
#
#app_trans_url: https://gateway.95516.com/gateway/api/appTransReq.do
#front_trans_url: https://gateway.95516.com/gateway/api/frontTransReq.do
#back_trans_url: https://gateway.95516.com/gateway/api/backTransReq.do
#card_back_trade: https://gateway.95516.com/gateway/api/cardTransReq.do
#single_query_url: https://gateway.95516.com/gateway/api/queryTrans.do
#batch_trans_url: https://gateway.95516.com/gateway/api/batchTrans.do
#file_trans_url: https://filedownload.95516.com/
# ========================================================================