# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u6807\u9898')),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': '\u95e8\u7968',
                'verbose_name_plural': '\u95e8\u7968',
            },
        ),
    ]
