# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_disneyticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='disneyticket',
            name='valid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
