# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0006_auto_20160519_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disneyticket',
            name='purchace_notes',
            field=models.TextField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u987b\u77e5'),
        ),
        migrations.AlterField(
            model_name='disneyticket',
            name='ticket_intro',
            field=models.TextField(blank=True, null=True, verbose_name='\u5957\u9910\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='disneyticket',
            name='vip_channel',
            field=models.TextField(blank=True, null=True, verbose_name='VIP\u901a\u9053'),
        ),
    ]
