# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0009_auto_20160519_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disneyticket',
            old_name='valid_date',
            new_name='validity',
        ),
    ]
