# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0010_auto_20160519_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disneyticket',
            name='purchace_notes',
        ),
        migrations.RemoveField(
            model_name='disneyticket',
            name='ticket_intro',
        ),
        migrations.AlterField(
            model_name='disneyticket',
            name='validity',
            field=models.DateField(blank=True, null=True, verbose_name='\u6709\u6548\u671f'),
        ),
    ]
