# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 06:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0012_remove_disneyticket_vip_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='disneyticket',
            name='vip_channel',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='VIP\u901a\u9053'),
        ),
    ]
