# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 14:49
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0014_auto_20160520_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disneyticket',
            name='intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u5957\u9910\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='disneyticket',
            name='purchase_notes',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u987b\u77e5'),
        ),
        migrations.AlterField(
            model_name='disneyticket',
            name='vip_channel',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='VIP\u901a\u9053'),
        ),
    ]
