# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import vip.utils


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0015_auto_20160521_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=vip.utils.get_ticket_cover_upload_path, verbose_name='\u5c01\u9762\u56fe'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u540d\u79f0'),
        ),
    ]
