# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0019_auto_20160523_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermerchandise',
            name='likes',
        ),
        migrations.AddField(
            model_name='usermerchandise',
            name='disney_likes',
            field=models.ManyToManyField(blank=True, to='merchandise.DisneyTicket', verbose_name='\u5df2\u6536\u85cf\u8fea\u58eb\u5c3c\u95e8\u7968'),
        ),
    ]
