# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0024_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='related_cities',
            field=models.ManyToManyField(to='merchandise.City', verbose_name='\u5173\u8054\u57ce\u5e02'),
        ),
    ]
