# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0025_ticket_related_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='related_cities',
            field=models.ManyToManyField(related_name='tickets', to='merchandise.City', verbose_name='\u5173\u8054\u57ce\u5e02'),
        ),
    ]
