# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0023_delete_city'),
        ('merchandise', '0026_auto_20160530_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='registrar.UserLabel', verbose_name='\u6807\u7b7e'),
        ),
    ]
