# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import vip.utils


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0027_ticket_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, upload_to=vip.utils.get_commercial_upload_path, verbose_name='\u5c01\u9762')),
                ('display', models.BooleanField(default=False, verbose_name='\u662f\u5426\u663e\u793a')),
            ],
            options={
                'verbose_name': '\u5e7f\u544a',
                'verbose_name_plural': '\u5e7f\u544a',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='registrar.UserLabel', verbose_name='\u5173\u8054\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='merchandise.Ticket', verbose_name='\u5173\u8054\u5546\u54c1'),
        ),
    ]
