# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0028_auto_20160530_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisneyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=11, verbose_name='\u8ba2\u5355\u53f7')),
                ('identification', models.CharField(max_length=18, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('entry_date', models.DateField(verbose_name='\u5165\u56ed\u65f6\u95f4')),
                ('pickup', models.BooleanField(verbose_name='\u662f\u5426\u63a5\u9001')),
                ('shipping_address', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u6536\u7968\u5730\u5740')),
                ('count', models.IntegerField(verbose_name='\u6570\u91cf')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disney_orders', to='merchandise.UserMerchandise')),
            ],
            options={
                'verbose_name': '\u8fea\u58eb\u5c3c\u95e8\u7968\u8ba2\u5355',
                'verbose_name_plural': '\u8fea\u58eb\u5c3c\u95e8\u7968\u8ba2\u5355',
            },
        ),
        migrations.AddField(
            model_name='disneyticket',
            name='pickup_rate',
            field=models.FloatField(default=0, verbose_name='\u63a5\u9001\u4ef7\u683c'),
        ),
        migrations.AddField(
            model_name='disneyorder',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='merchandise.DisneyTicket'),
        ),
    ]
