# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0029_auto_20160601_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='disneyticket',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u8d77\u59cb\u65e5\u671f'),
        ),
    ]
