# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 03:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0030_disneyticket_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disneyticket',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='\u8d77\u59cb\u65e5\u671f'),
        ),
    ]
