# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0031_auto_20160601_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disneyorder',
            name='entry_date',
        ),
    ]
