# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0032_remove_disneyorder_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='disneyorder',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
