# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0033_disneyorder_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AerospaceTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='merchandise.Ticket')),
                ('intro', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u5957\u9910\u4ecb\u7ecd')),
                ('purchase_notes', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u987b\u77e5')),
            ],
            options={
                'verbose_name': '\u5b87\u822a\u5957\u9910',
                'verbose_name_plural': '\u5b87\u822a\u5957\u9910',
            },
            bases=('merchandise.ticket',),
        ),
        migrations.RemoveField(
            model_name='illustrationimage',
            name='ticket',
        ),
        migrations.AlterField(
            model_name='disneyorder',
            name='pickup',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u63a5\u9001'),
        ),
        migrations.DeleteModel(
            name='IllustrationImage',
        ),
        migrations.AddField(
            model_name='usermerchandise',
            name='aero_likes',
            field=models.ManyToManyField(blank=True, to='merchandise.AerospaceTicket', verbose_name='\u5df2\u6536\u85cf\u822a\u7a7a\u5957\u9910'),
        ),
    ]
