# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0034_auto_20160601_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertOrder',
            fields=[
                ('disneyorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='merchandise.DisneyOrder')),
            ],
            options={
                'verbose_name': '\u6f14\u5531\u4f1a\u7968\u8ba2\u5355',
                'verbose_name_plural': '\u6f14\u5531\u4f1a\u7968\u8ba2\u5355',
            },
            bases=('merchandise.disneyorder',),
        ),
        migrations.AlterField(
            model_name='concertticket',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u65f6\u95f4'),
        ),
    ]
