# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0035_auto_20160602_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disneyorder',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='concertorder',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u6536\u7968\u5730\u5740'),
        ),
    ]
