# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0037_auto_20160602_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a',
            name='base_ptr',
        ),
        migrations.RemoveField(
            model_name='disneyorder',
            name='purchaser',
        ),
        migrations.RemoveField(
            model_name='disneyorder',
            name='ticket_type',
        ),
        migrations.DeleteModel(
            name='A',
        ),
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.DeleteModel(
            name='DisneyOrder',
        ),
    ]
