# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0041_concertorder_disneyorder_ticketorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertorder',
            name='purchaser',
        ),
        migrations.RemoveField(
            model_name='concertorder',
            name='ticketorder_ptr',
        ),
        migrations.DeleteModel(
            name='ConcertOrder',
        ),
    ]
