# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0046_auto_20160607_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='status',
            field=models.CharField(choices=[('P', '\u5df2\u4ed8\u6b3e'), ('N', '\u5f85\u4ed8\u6b3e'), ('C', '\u53d6\u6d88\u4ea4\u6613')], default='N', max_length=1, verbose_name='\u4ed8\u6b3e\u72b6\u6001'),
        ),
    ]
