# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0047_auto_20160608_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='transaction_info',
            field=models.TextField(blank=True, verbose_name='\u94f6\u8054\u4ea4\u6613\u4fe1\u606f'),
        ),
    ]
