# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0049_auto_20160608_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cover',
        ),
    ]
