# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import vip.utils


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0050_remove_ticket_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='detail_cover',
            field=models.ImageField(null=True, upload_to=vip.utils.get_ticket_detail_cover_upload_path, verbose_name='\u8be6\u60c5\u9875\u5c01\u9762\u56fe'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='listing_cover',
            field=models.ImageField(null=True, upload_to=vip.utils.get_ticket_listing_cover_upload_path, verbose_name='\u5217\u8868\u9875\u5c01\u9762\u56fe'),
        ),
    ]
