# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0054_auto_20160616_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertticket',
            options={'verbose_name': '\u6f14\u5531\u4f1a\u5361', 'verbose_name_plural': '\u6f14\u5531\u4f1a\u5361'},
        ),
        migrations.AlterModelOptions(
            name='disneyticket',
            options={'verbose_name': '\u8fea\u58eb\u5c3c\u516c\u56ed\u5361', 'verbose_name_plural': '\u8fea\u58eb\u5c3c\u516c\u56ed\u5361'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': '\u5361', 'verbose_name_plural': '\u5361'},
        ),
    ]
