# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0056_auto_20160621_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertticket',
            name='entry_notes',
            field=models.TextField(blank=True, verbose_name='\u5165\u573a\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='disneyticket',
            name='entry_notes',
            field=models.TextField(blank=True, verbose_name='\u5165\u573a\u987b\u77e5'),
        ),
    ]
