# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0057_auto_20160623_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='caption',
            field=models.CharField(default='', max_length=30, verbose_name='\u63a8\u8350\u63cf\u8ff0'),
            preserve_default=False,
        ),
    ]
