# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0058_ticket_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='caption',
            field=models.CharField(max_length=25, verbose_name='\u63a8\u8350\u63cf\u8ff0'),
        ),
    ]
