# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0060_auto_20160629_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermerchandise',
            name='account_balance',
            field=models.FloatField(default=0.0, verbose_name='\u63d0\u73b0\u91d1\u989d'),
        ),
    ]
