# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchandise', '0061_usermerchandise_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d7\u76ca\u4eba'),
        ),
    ]
