# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0062_ticketorder_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisneySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('inventory', models.IntegerField(verbose_name='\u4f59\u7968\u91cf')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise.DisneyTicket', verbose_name='\u5546\u54c1')),
            ],
            options={
                'verbose_name': ('\u8fea\u58eb\u5c3c\u65f6\u95f4\u8868',),
                'verbose_name_plural': ('\u8fea\u58eb\u5c3c\u65f6\u95f4\u8868',),
            },
        ),
    ]
