# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0063_disneyschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disneyschedule',
            options={'verbose_name': ('\u8fea\u58eb\u5c3c\u65f6\u95f4\u8868',), 'verbose_name_plural': '\u8fea\u58eb\u5c3c\u65f6\u95f4\u8868'},
        ),
    ]
