# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0065_auto_20160704_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disneyschedule',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='merchandise.DisneyTicket', verbose_name='\u5546\u54c1'),
        ),
    ]
