# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0067_disneyorder_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermerchandise',
            name='level',
            field=models.IntegerField(choices=[(1, '\u4e00\u7ea7\u7528\u6237'), (2, '\u4e8c\u7ea7\u7528\u6237'), (3, '\u4e09\u7ea7\u7528\u6237')], default=3, verbose_name='\u7528\u6237\u7b49\u7ea7'),
        ),
    ]
