# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0073_auto_20160711_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrecord',
            name='status',
            field=models.IntegerField(choices=[(-1, '\u672a\u63d0\u73b0'), (0, '\u63d0\u73b0\u7533\u8bf7\u4e2d'), (1, '\u5df2\u63d0\u73b0')], default=-1, verbose_name='\u63d0\u73b0\u72b6\u6001'),
        ),
    ]
