# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0076_withdrawrecord_apply_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermerchandise',
            name='credits',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u79ef\u5206'),
        ),
    ]
